@Library('shared-library@master') _
pipeline {
    agent any
environment {
        JFROG_ID = credentials('jfrogid')
       bn = "${BUILD_NUMBER}"
    url = "https://jfrgfreetst.jfrog.io/artifactory/api/storage/example-repo-local"
    folder_path = curlmethod(url,JFROG_ID,bn)
    Path = "${url}/${folder_path}/?sort"
   
      }
     
    stages {
        stage('Hello') {
            steps {
                echo " job name is ${env.JOB_NAME}"
            }
        }
        stage("Using curl example") {
            steps {
                script {
                    //final String url = "https://jfrgfreetst.jfrog.io/artifactory/api/storage/example-repo-local/?sort"

                   

                  //print("the folder path is:"+' '+folder_path+" and image is: "+image_name)
                   //print(Path)
                }
            }
        }
    }
}

